[programs.localnet]
create_account = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/mlim/.config/solana/id.json"

[scripts]
test = "ts-mocha -t 300000 tests/*.spec.ts"
